# .streamlit/config.toml

[theme]
# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "light"

# Primary accent color for interactive elements.
primaryColor = "#d97706" # A vibrant teal/cyan

# Background color for the main content area.
backgroundColor = "#e4be88ff"

# Background color for sidebar and most interactive widgets.
secondaryBackgroundColor = "#C9E4CA"

# Color used for almost all text.
textColor = "#74272ff"

# Font family for all text in the app.
# Can be "serif", "sans serif", or "monospace".
# "sans serif" is a great choice for a clean, modern look.
font = "sans serif"
